name: Release Next Version

on:
  push:
    branches:
      - action-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Artifact
        uses: ./.github/workflows/build-artifact.yaml
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Print Contents
        run: ls
