name: Release Next Version

on:
  push:
    branches:
      - action-test

jobs:
  build:
    uses: ./.github/workflows/build-artifact.yaml

  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Contents
        run: ls
